In [0]:
import OOC
import string
import random
import numpy as np
import test

In [0]:
"""
  This function generates n differents random colors.
  A color is defined by a R,G,B couple : [R,G,B]
  Returns a list of format : [[R1,G1,B1], [R2,G2,B3] ... [Rn,Bn,Gn]] for n colors
"""
def random_colors(n):
  colors = []
  r = int(random.random() * 256)
  g = int(random.random() * 256)
  b = int(random.random() * 256)
  step = 256 / n
  for i in range(n):
    r += step
    g += step
    b += step
    r = int(r) % 256
    g = int(g) % 256
    b = int(b) % 256
    colors.append([r,g,b]) 
  return colors

In [0]:
"""
  Create a ppm file.
  Parameters :
    - filename : the name of the file
    - colordict : a dict where keys are labels and values are the corresponding color [R,G,B]
    - graph : the graph we want to represent as a ppm file
    - max_value : max value of the color ; 255 if not specified.
    
    Returns : None but create a ppm file in the specified folder.
"""
def create_ppm_file(filename, colordict, graph, max_value = 255):
    """
    Create a ppm file
    """
    with open(filename, mode='w+', encoding='utf8') as f:
    
        f.write("P3\n") # magic number that identifies the file type (ppm in this case)
        f.write("# " + str(filename) + "\n") # lines that starts with # are ignored when we read the file
        
        f.write(str(graph.dim_x) + " " + str(graph.dim_y) + "\n")
        f.write(str(max_value) + "\n")
        
        for vertice in graph.vertices:
            f.write(str(colordict.get(vertice.label)[0]) + " " + str(colordict.get(vertice.label)[1]) + " " +str(colordict.get(vertice.label)[2]) +"\n")
            
        
        

In [0]:
graph = test.fill_graph_with_file("file.graph")
sub = test.divide_blocks(graph,6,3)
#test = test.BlocThinning(sub[0],sub[1],sub[0].cut)


# Test : we give 4 random labels :

random_label = ["a","b","c","d"] # Test : we give 4 random labels

for x in graph.vertices:
    x.label = random.choice(random_label)

B =
 [[00 01 02 03 04 05]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]
C =
 [[[00 01 02]
  [10 11 12]
  [20 21 22]
  [30 31 32]
  [40 41 42]
  [50 51 52]]

 [[03 04 05]
  [13 14 15]
  [23 24 25]
  [33 34 35]
  [43 44 45]
  [53 54 55]]]


In [0]:
labels = set([x.label for x in graph.vertices])
labels

{'a', 'b', 'c', 'd'}

In [0]:
colors = random_colors(len(labels))
colors

[[21, 56, 248], [85, 120, 56], [149, 184, 120], [213, 248, 184]]

In [0]:
dict_colors = dict(zip(labels, colors)) # map colors and labels together
dict_colors

{'a': [213, 248, 184],
 'b': [21, 56, 248],
 'c': [149, 184, 120],
 'd': [85, 120, 56]}

In [0]:
create_ppm_file("ppm_test.ppm", dict_colors, graph) # create a ppm file - you can open it by using Irfanview : https://www.irfanview.net 

https://stackoverflow.com/questions/15890743/how-can-you-split-a-list-every-x-elements-and-add-those-x-amount-of-elements-to